// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy6PZ3I8uEDY8OxLOXvAsZd2GE02cOB5c',
    appId: '1:834015954:web:063db7a8c295439516530b',
    messagingSenderId: '834015954',
    projectId: 'daon-launchpad',
    authDomain: 'daon-launchpad.firebaseapp.com',
    storageBucket: 'daon-launchpad.firebasestorage.app',
    measurementId: 'G-KPLDV13WQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbTvn0z5L5Q5-kgYpKjAGTjxcqkrivaRM',
    appId: '1:834015954:android:076b164747a43ba416530b',
    messagingSenderId: '834015954',
    projectId: 'daon-launchpad',
    storageBucket: 'daon-launchpad.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmf6KZNAjCEzNK3kSZbEMvaUf_kONl1k8',
    appId: '1:834015954:ios:c54e434a42c0fa9a16530b',
    messagingSenderId: '834015954',
    projectId: 'daon-launchpad',
    storageBucket: 'daon-launchpad.firebasestorage.app',
    androidClientId: '834015954-j7fj5mg8v7gg73cvu9nk81o34qh36hvh.apps.googleusercontent.com',
    iosClientId: '834015954-bi8ft0bkmfhbaj66ace3l20ovq5e9uj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectDaon',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmf6KZNAjCEzNK3kSZbEMvaUf_kONl1k8',
    appId: '1:834015954:ios:c54e434a42c0fa9a16530b',
    messagingSenderId: '834015954',
    projectId: 'daon-launchpad',
    storageBucket: 'daon-launchpad.firebasestorage.app',
    androidClientId: '834015954-j7fj5mg8v7gg73cvu9nk81o34qh36hvh.apps.googleusercontent.com',
    iosClientId: '834015954-bi8ft0bkmfhbaj66ace3l20ovq5e9uj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectDaon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy6PZ3I8uEDY8OxLOXvAsZd2GE02cOB5c',
    appId: '1:834015954:web:05e068371b39e48216530b',
    messagingSenderId: '834015954',
    projectId: 'daon-launchpad',
    authDomain: 'daon-launchpad.firebaseapp.com',
    storageBucket: 'daon-launchpad.firebasestorage.app',
    measurementId: 'G-QM8W38DVQD',
  );
}
